health = "Health"
tm="Time Management"
expenses= "Expenses"
professional_growth="Work/Life"
personal_growth="Personal/Life"
habits = "Habit Tracking"
sex="Sex/Life"

hr="Hour"
bool="Boolean"
num="Number"
enum="Categorical"
